// Generated by scripts/generate-bank-index.mjs; do not edit.
export const PUBLIC_BANK_INDEX_FILES = {
  "igcse": "igcse.v1-af4eeeb84ca0.json",
  "igcse-additional": "igcse-additional.v1-ee0c69b63e73.json",
  "ib-hl": "ib-hl.v1-9e2f72b63aaa.json",
  "ib-sl": "ib-sl.v1-5d2101fe71df.json",
  "ib-ai-hl": "ib-ai-hl.v1-7ea13753a09e.json",
  "ib-ai-sl": "ib-ai-sl.v1-89a5f3b6b9e3.json",
  "ib-chemistry-hl": "ib-chemistry-hl.v1-1cd89edee27a.json",
  "ib-chemistry-sl": "ib-chemistry-sl.v1-6992cb3473d1.json",
  "ib-physics-hl": "ib-physics-hl.v1-05471c124342.json",
  "ib-physics-sl": "ib-physics-sl.v1-caae3530bde8.json"
} as const;
