// Generated by scripts/generate-bank-index.mjs; do not edit.
export const PUBLIC_BANK_INDEX_FILES = {
  "igcse": "igcse.v1-d2a1f03d4b4b.json",
  "igcse-additional": "igcse-additional.v1-3e2f56806073.json",
  "ib-hl": "ib-hl.v1-294d7d4b5d7d.json",
  "ib-sl": "ib-sl.v1-353230772f4b.json",
  "ib-ai-hl": "ib-ai-hl.v1-a651f6921e65.json",
  "ib-ai-sl": "ib-ai-sl.v1-1c0a21745dfa.json",
  "ib-chemistry-hl": "ib-chemistry-hl.v1-1cd89edee27a.json",
  "ib-chemistry-sl": "ib-chemistry-sl.v1-6992cb3473d1.json"
} as const;
