// Generated by scripts/generate-bank-index.mjs; do not edit.
export const PUBLIC_BANK_INDEX_FILES = {
  "igcse": "igcse.v1-af4eeeb84ca0.json",
  "igcse-additional": "igcse-additional.v1-ee0c69b63e73.json",
  "ib-hl": "ib-hl.v1-9e2f72b63aaa.json",
  "ib-sl": "ib-sl.v1-5d2101fe71df.json",
  "ib-ai-hl": "ib-ai-hl.v1-7ea13753a09e.json",
  "ib-ai-sl": "ib-ai-sl.v1-89a5f3b6b9e3.json",
  "ib-chemistry-hl": "ib-chemistry-hl.v1-7a56eef20520.json",
  "ib-chemistry-sl": "ib-chemistry-sl.v1-95d2c28ef8a2.json",
  "ib-physics-hl": "ib-physics-hl.v1-4b1f858d6f89.json",
  "ib-physics-sl": "ib-physics-sl.v1-e2d480cb3b2e.json",
  "ib-biology-hl": "ib-biology-hl.v1-a86881fb25ac.json",
  "ib-biology-sl": "ib-biology-sl.v1-313ffdd53e4f.json"
} as const;
