import { beforeEach, describe, expect, it, vi } from "vitest";
import { POST } from "@/app/api/billing/lifetime/checkout/route";
const m=vi.hoisted(()=>({rpc:vi.fn(),list:vi.fn(),retrieve:vi.fn(),create:vi.fn(),access:vi.fn(),purchase:vi.fn()}));
vi.mock("@/lib/supabase/server",()=>({createClient:async()=>({auth:{getUser:async()=>({data:{user:{id:"user_1",email:"u@example.com"}}})}})}));
vi.mock("@/lib/supabase/admin",()=>({createAdminClient:()=>({rpc:m.rpc,from:()=>({select:()=>({eq:()=>({eq:()=>({limit:m.purchase})})})})})}));
vi.mock("@/lib/stripe-config",()=>({getStripeConfig:()=>({secretKey:"sk_test",siteUrl:"https://example.test",singleMonthlyPriceId:"price_month",singleAnnualPriceId:"price_year",customMonthlyPriceId:"price_cm",customAnnualPriceId:"price_ca",allMonthlyPriceId:"price_allm",allAnnualPriceId:"price_ally"}),isStripeBillingEnabled:()=>true}));
vi.mock("@/lib/stripe",()=>({createStripeClient:()=>({subscriptions:{list:m.list,retrieve:m.retrieve},checkout:{sessions:{create:m.create}}})}));
vi.mock("@/lib/custom-bundle-access",()=>({fetchAccessEntitlements:m.access}));
const subscription=()=>({id:"sub_1",customer:"cus_1",status:"active",metadata:{user_id:"user_1",product_id:"bank_igcse",billing_interval:"monthly",price_id:"price_month"},schedule:null,pending_update:null,cancel_at_period_end:false,cancel_at:null,current_period_start:1700000000,current_period_end:1800000000,items:{data:[{id:"si_1",quantity:1,price:{id:"price_month",currency:"usd",recurring:{interval:"month"}}}]}});
beforeEach(()=>{vi.clearAllMocks();m.purchase.mockResolvedValue({data:[],error:null});m.access.mockResolvedValue({rows:[],error:null});m.rpc.mockImplementation(async(n:string)=>n==="get_stripe_customer_id"?{data:"cus_1",error:null}:n==="get_checkout_price_catalog"?{data:[{price_id:"price_month",product_id:"bank_igcse",billing_interval:"monthly",active:true}],error:null}:n==="reserve_lifetime_conversion"||n==="attach_lifetime_conversion_session"?{data:true,error:null}:{data:null,error:Error(n)});m.list.mockResolvedValue({data:[subscription()],has_more:false});m.retrieve.mockResolvedValue(subscription());m.create.mockResolvedValue({id:"cs_test_1",url:"https://checkout.test",expires_at:1800000000});});
describe("lifetime subscription-conversion checkout",()=>{
it("reserves a validated owned target before creating a one-time $299 payment session",async()=>{const res=await POST();expect(res.status).toBe(200);expect(m.rpc.mock.calls.findIndex(([n])=>n==="reserve_lifetime_conversion")).toBeLessThan(m.create.mock.invocationCallOrder[0]-1);expect(m.create).toHaveBeenCalledWith(expect.objectContaining({mode:"payment",line_items:[expect.objectContaining({price_data:expect.objectContaining({unit_amount:29900})})],payment_intent_data:expect.objectContaining({metadata:expect.objectContaining({conversion_intent_id:expect.any(String)})})}),expect.anything());expect(m.rpc).toHaveBeenCalledWith("attach_lifetime_conversion_session",expect.objectContaining({p_session_id:"cs_test_1"}));});
it("rejects foreign or stacked subscriptions before reserving",async()=>{m.list.mockResolvedValue({data:[subscription(),{...subscription(),id:"sub_2"}],has_more:false});expect((await POST()).status).toBe(409);expect(m.rpc).not.toHaveBeenCalledWith("reserve_lifetime_conversion",expect.anything());expect(m.create).not.toHaveBeenCalled();});
it("retains the reservation if Stripe creation has uncertain outcome",async()=>{m.create.mockRejectedValue(Error("timeout"));expect((await POST()).status).toBe(503);expect(m.rpc).toHaveBeenCalledWith("reserve_lifetime_conversion",expect.anything());expect(m.rpc).not.toHaveBeenCalledWith("release_billing_checkout",expect.anything());});
});
