import { beforeEach, describe, expect, it, vi } from "vitest";
import { POST } from "./cancellation/route";

const m = vi.hoisted(() => ({ editor: "true", getUser: vi.fn(), rpc: vi.fn(), reserve: vi.fn(), release: vi.fn(), listSubs: vi.fn(), listSessions: vi.fn(), listInvoices: vi.fn(), update: vi.fn(), retrieve: vi.fn(), billing: true, userId: "user_1", customerId: "cus_1", subscription: null as unknown as ReturnType<typeof sub> }));
vi.mock("@/lib/supabase/server", () => ({ createClient: async () => ({ auth: { getUser: m.getUser } }) }));
vi.mock("@/lib/supabase/admin", () => ({ createAdminClient: () => ({ rpc: m.rpc }) }));
vi.stubEnv("STRIPE_PLAN_EDITOR_ENABLED", "true");
vi.mock("node:crypto", async (importOriginal) => ({ ...(await importOriginal<typeof import("node:crypto")>()), randomUUID: () => "intent_1" }));
vi.mock("@/lib/stripe-config", () => ({ isStripeBillingEnabled: () => m.billing, getStripeConfig: () => ({ secretKey: "sk_test_fake" }) }));
vi.mock("@/lib/stripe", () => ({ createStripeClient: () => ({ subscriptions: { list: m.listSubs, update: m.update, retrieve: m.retrieve }, checkout: { sessions: { list: m.listSessions } }, invoices: { list: m.listInvoices } }) }));
const req = (intent: "cancel" | "undo" = "cancel", origin = "https://app.test") => new Request("https://app.test/api/billing/subscription/cancellation", { method: "POST", headers: { origin, "content-type": "application/json" }, body: JSON.stringify({ intent }) });
const sub = () => ({ id: "sub_1", customer: "cus_1", status: "active", metadata: { user_id: "user_1" }, pending_update: null, schedule: null, cancel_at: null as number | null, cancel_at_period_end: false, items: { data: [{ id: "si_1", current_period_end: 1900000000 }] } });
beforeEach(() => { vi.clearAllMocks(); m.billing = true; m.userId = "user_1"; m.customerId = "cus_1"; m.subscription = sub(); m.getUser.mockResolvedValue({ data: { user: { id: m.userId } } }); m.rpc.mockImplementation(async (name: string) => name === "get_stripe_customer_id" ? { data: m.customerId, error: null } : name === "reserve_billing_checkout" ? { data: m.reserve(), error: null } : name === "release_billing_checkout" ? { data: m.release(), error: null } : { data: true, error: null }); m.reserve.mockReturnValue(true); m.release.mockReturnValue(true); m.listSubs.mockResolvedValue({ data: [m.subscription], has_more: false }); m.listSessions.mockResolvedValue({ data: [], has_more: false }); m.listInvoices.mockResolvedValue({ data: [], has_more: false }); m.update.mockImplementation(async (_id: string, params: { cancel_at_period_end: boolean }) => ({ ...m.subscription, ...params })); m.retrieve.mockImplementation(async () => m.subscription); });
describe("subscription cancellation route", () => {
  it("rejects unauthenticated requests", async () => { m.getUser.mockResolvedValue({ data: { user: null } }); const r = await POST(req()); expect(r.status).toBe(401); expect(m.rpc).not.toHaveBeenCalled(); });
  it("rejects cross-origin requests", async () => { const r = await POST(req("cancel", "https://evil.test")); expect(r.status).toBe(403); expect(m.getUser).not.toHaveBeenCalled(); });
  it("rejects a mismatched subscription owner", async () => { m.subscription.metadata.user_id = "other"; const r = await POST(req()); expect(r.status).toBe(409); expect(m.update).not.toHaveBeenCalled(); });
  it("fails closed when Checkout is open", async () => { m.listSessions.mockResolvedValue({ data: [{ id: "cs_1" }], has_more: false }); const r = await POST(req()); expect(r.status).toBe(409); expect(m.update).not.toHaveBeenCalled(); });
  it("rejects reservation overlap", async () => { m.reserve.mockReturnValue(false); const r = await POST(req()); expect(r.status).toBe(409); expect(m.listSubs).not.toHaveBeenCalled(); });
  it("sets and reads back period-end cancellation", async () => { m.update.mockImplementation(async () => ({ ...m.subscription, cancel_at_period_end: true })); m.retrieve.mockImplementation(async () => ({ ...m.subscription, cancel_at_period_end: true })); const r = await POST(req()); expect(r.status).toBe(200); expect(m.update).toHaveBeenCalledWith("sub_1", { cancel_at_period_end: true }, expect.objectContaining({ idempotencyKey: expect.stringMatching(/^pastpaperprep-cancel-/), timeout: 30000 })); expect(m.release).toHaveBeenCalled(); expect((await r.json()).effectiveAt).toBe(new Date(1900000000 * 1000).toISOString()); });
  it("undoes cancellation without early entitlement mutation", async () => { m.subscription.cancel_at_period_end = true; m.update.mockImplementation(async () => ({ ...m.subscription, cancel_at_period_end: false })); m.retrieve.mockImplementation(async () => ({ ...m.subscription, cancel_at_period_end: false })); const r = await POST(req("undo")); expect(r.status).toBe(200); expect(m.update).toHaveBeenCalledWith("sub_1", { cancel_at_period_end: false }, expect.any(Object)); expect(m.rpc).not.toHaveBeenCalledWith("grant_entitlement", expect.anything()); });
  it("retains lease after ambiguous update failure", async () => { m.update.mockRejectedValue(new Error("timeout")); const r = await POST(req()); expect(r.status).toBe(503); expect(m.release).not.toHaveBeenCalled(); });
  it("returns idempotently when desired state already exists", async () => { m.subscription.cancel_at_period_end = true; m.retrieve.mockImplementation(async () => m.subscription); const r = await POST(req()); expect(r.status).toBe(200); expect(m.update).not.toHaveBeenCalled(); });
  it("stays disabled by default and never reserves billing", async () => { process.env.STRIPE_PLAN_EDITOR_ENABLED = "false"; try { expect((await POST(req())).status).toBe(404); expect(m.reserve).not.toHaveBeenCalled(); } finally { process.env.STRIPE_PLAN_EDITOR_ENABLED = "true"; } });
  it("does not override a separately scheduled cancellation date", async () => { m.subscription.cancel_at = 1800000000; expect((await POST(req())).status).toBe(409); expect(m.update).not.toHaveBeenCalled(); });
  it("does not report success when reservation release fails", async () => { m.release.mockReturnValue(false); m.retrieve.mockResolvedValue({ ...m.subscription, cancel_at_period_end: true }); expect((await POST(req())).status).toBe(503); });
  it("does not claim an old renewal date if the readback period changed", async () => { m.retrieve.mockResolvedValue({ ...m.subscription, cancel_at_period_end: true, items: { data: [{ id: "si_1", current_period_end: 1900000001 }] } }); expect((await POST(req())).status).toBe(503); expect(m.release).not.toHaveBeenCalled(); });
});
